name       : ipscan
version    : 3.4.2
release    : 2
source     :
    - https://github.com/angryziber/ipscan/archive/3.4.2.tar.gz : 378fbd66a97948a07654562089aa92ca0a8d56643a4b18c258c32de5af2c9bdf
license    : GPL-2.0
component  : network.util
summary    : Angry IP Scanner
description: |
    Angry IP Scanner
builddeps  :
    - apache-ant
    - git
    - rpm
rundeps    :
    - openjdk-8
build      : |
    ant linux64
install    : |
    install -D -m 00755 $pkgfiles/ipscan $installdir/usr/bin/ipscan
    install -D -m 00644 $pkgfiles/ipscan.desktop $installdir/usr/share/applications/ipscan.desktop
    install -D -m 00755 dist/ipscan-linux64-3.4.2.jar $installdir/usr/share/ipscan/ipscan-linux64-3.4.2.jar
    install -D -m 00644 resources/images/icon256.png $installdir/usr/share/pixmaps/ipscan.png
