name       : ipscan
version    : 3.7.0
release    : 5
source     :
    - https://github.com/angryziber/ipscan/archive/3.7.0.tar.gz : abde3211db69ea714651cf808a208923712c99ddc78dbe930bb10ea29d998032
license    : GPL-2.0-or-later
homepage   : https://angryip.org/
component  : network.util
summary    : Angry IP Scanner
description: |
    Angry IP Scanner
networking : yes
builddeps  :
    - openjdk-8
rundeps    :
    - openjdk-8
environment: |
    export GRADLE_USER_HOME=$workdir/.gradle
setup      : |
    # patch build.gradle file so we skip building .deb and .rpm packages, we only need .jar
    # also skip minimizing jar because it is failing for some reason
    %patch -p1 < $pkgfiles/0001-disable-deb-rpm-minimize.patch
build      : |
    %make linux64
install    : |
    install -D -m 00755 $pkgfiles/ipscan $installdir/usr/bin/ipscan
    install -D -m 00644 $pkgfiles/ipscan.desktop $installdir/usr/share/applications/ipscan.desktop
    install -D -m 00755 $workdir/build/libs/ipscan-%version%-linux64-%version%.jar $installdir/usr/share/ipscan/ipscan.jar
    install -D -m 00644 $workdir/build/resources/main/images/icon256.png $installdir/usr/share/pixmaps/ipscan.png
