name       : ipscan
version    : 3.5.5
release    : 3
source     :
    - https://github.com/angryziber/ipscan/archive/3.5.5.tar.gz : 0b1cb83442277b369503e82c80ee3e345e8de01464aaa0fc69f616fa6493a232
license    : GPL-2.0
component  : network.util
summary    : Angry IP Scanner
description: |
    Angry IP Scanner
networking : yes
builddeps  :
    - openjdk-8
rundeps    :
    - openjdk-8
environment: |
    export GRADLE_USER_HOME=$workdir/.gradle
setup      : |
    # patch build.gradle file so we skip building .deb and .rpm packages, we only need .jar
    %patch -p1 < $pkgfiles/0001-disable-deb-rpm.patch
build      : |
    %make linux64
install    : |
    install -D -m 00755 $pkgfiles/ipscan $installdir/usr/bin/ipscan
    install -D -m 00644 $pkgfiles/ipscan.desktop $installdir/usr/share/applications/ipscan.desktop
    install -D -m 00755 $workdir/build/libs/ipscan-%version%-linux64-%version%.jar $installdir/usr/share/ipscan/ipscan.jar
    install -D -m 00644 $workdir/build/resources/main/images/icon256.png $installdir/usr/share/pixmaps/ipscan.png
