name       : ipscan
version    : 3.8.2
release    : 13
source     :
    - https://github.com/angryziber/ipscan/archive/3.8.2.tar.gz : 32bc6713ea1599aed739f867ac660228e1f6422f76578e114adeca2d4c7c0578
license    : GPL-2.0-or-later
homepage   : https://angryip.org/
component  : network.util
summary    : Angry IP Scanner - Fast network scanner
description: |
    ipscan scans the network for reachable hosts and more.
networking : yes
builddeps  :
    - gradle
    - openjdk-17
rundeps    :
    - openjdk-17
environment: |
    export JAVA_HOME=/usr/lib64/openjdk-17
    export PATH=$JAVA_HOME/bin:$PATH

    export GRADLE_USER_HOME=$workdir/.gradle
setup      : |
    # This patch does the following:
    # - Uses a Gradle property for version detection instead of Git
    # - Disables building of deb and rpm packages
    # - Disables minimization to avoid build failure
    %patch -p1 < $pkgfiles/fix-build-gradle.patch
build      : |
    ./gradlew -PipscanVersion=%version% linux64
install    : |
    install -Dm00755 $pkgfiles/ipscan -t $installdir/usr/bin
    install -Dm00644 $pkgfiles/ipscan.desktop -t $installdir/usr/share/applications
    install -Dm00644 $workdir/build/libs/ipscan-%version%-linux64-%version%.jar $installdir/usr/share/ipscan/ipscan.jar
    
    install -Dm00644 $workdir/build/resources/main/images/icon.svg $installdir/usr/share/icons/hicolor/scalable/apps/ipscan.svg
    for i in 32 48 128 256; do
        install -Dm00644 $workdir/build/resources/main/images/icon${i}.png $installdir/usr/share/icons/hicolor/${i}x${i}/apps/ipscan.png
    done
