name       : ipscan
version    : 3.7.2
release    : 7
source     :
    - https://github.com/angryziber/ipscan/archive/3.7.2.tar.gz : 550799948435877ff279a18b6e15dba4f6f69185eff6ce80798faf0a520ffa90
license    : GPL-2.0-or-later
homepage   : https://angryip.org/
component  : network.util
summary    : Angry IP Scanner - Fast network scanner
description: |
    ipscan scans the network for reachable hosts and more.
networking : yes
builddeps  :
    - gradle
rundeps    :
    - openjdk-11
setup      : |
    # This patch does the following:
    # - Uses a Gradle property for version detection instead of Git
    # - Disables building of deb and rpm packages
    # - Disables minimization to avoid build failure
    %patch -p1 < $pkgfiles/fix-build-gradle.patch
build      : |
    export GRADLE_USER_HOME=$workdir/.gradle
    gradle --no-daemon -PipscanVersion=%version% linux64
install    : |
    install -Dm00755 $pkgfiles/ipscan -t $installdir/usr/bin
    install -Dm00644 $pkgfiles/ipscan.desktop -t $installdir/usr/share/applications
    install -Dm00755 $workdir/build/libs/ipscan-%version%-linux64-%version%.jar $installdir/usr/share/ipscan/ipscan.jar
    install -Dm00644 $workdir/build/resources/main/images/icon256.png $installdir/usr/share/pixmaps/ipscan.png
